###
POST http://localhost:4000/postschool
Content-Type: application/json

{
    "name": "Escola privada 940498", 
    "location": "Kilamba kiaxi , Luanda",
    "email": "escola13@gmail.com",  
    "phone": "9839376486363",
    "type": 2 
}


###
GET http://localhost:4000/schools